package com.hj.oa.dao;

import com.hj.oa.bean.ApprovalList;
import com.hj.oa.bean.ApprovalListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApprovalListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_list
     *
     * @mbggenerated
     */
    int countByExample(ApprovalListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_list
     *
     * @mbggenerated
     */
    int deleteByExample(ApprovalListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_list
     *
     * @mbggenerated
     */
    int insert(ApprovalList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_list
     *
     * @mbggenerated
     */
    int insertSelective(ApprovalList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_list
     *
     * @mbggenerated
     */
    List<ApprovalList> selectByExample(ApprovalListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_list
     *
     * @mbggenerated
     */
    ApprovalList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_list
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ApprovalList record, @Param("example") ApprovalListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_list
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ApprovalList record, @Param("example") ApprovalListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApprovalList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApprovalList record);
}