package com.hj.oa.dao;

import com.hj.oa.bean.OutstockRecord;
import com.hj.oa.bean.OutstockRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutstockRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    int countByExample(OutstockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    int deleteByExample(OutstockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    int insert(OutstockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    int insertSelective(OutstockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    List<OutstockRecord> selectByExample(OutstockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    OutstockRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OutstockRecord record, @Param("example") OutstockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OutstockRecord record, @Param("example") OutstockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OutstockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OutstockRecord record);
}