package com.hj.oa.dao;

import com.hj.oa.bean.OutstockDetail;
import com.hj.oa.bean.OutstockDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutstockDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_detail
     *
     * @mbggenerated
     */
    int countByExample(OutstockDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_detail
     *
     * @mbggenerated
     */
    int deleteByExample(OutstockDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_detail
     *
     * @mbggenerated
     */
    int insert(OutstockDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_detail
     *
     * @mbggenerated
     */
    int insertSelective(OutstockDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_detail
     *
     * @mbggenerated
     */
    List<OutstockDetail> selectByExample(OutstockDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_detail
     *
     * @mbggenerated
     */
    OutstockDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OutstockDetail record, @Param("example") OutstockDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OutstockDetail record, @Param("example") OutstockDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OutstockDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OutstockDetail record);

	/** 
	* @Description: 批量出入详细记录
	* @param outDetails
	* @return int
	* @author mlsong
	* @date 2018年6月6日 下午2:21:10
	*/
	int insertList(List<OutstockDetail> outDetails);

	/** 
	* @Description: 
	* @param id
	* @return int
	* @author mlsong
	* @date 2018年6月26日 下午3:58:36
	*/
	int countProductSumByRecordId(Integer id);
	
}