package com.hj.oa.dao;

import com.hj.oa.bean.ProductOutstockRecord;
import com.hj.oa.bean.ProductOutstockRecordExample;
import com.hj.oa.bean.Role;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductOutstockRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_record
     *
     * @mbggenerated
     */
    int countByExample(ProductOutstockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_record
     *
     * @mbggenerated
     */
    int deleteByExample(ProductOutstockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_record
     *
     * @mbggenerated
     */
    int insert(ProductOutstockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_record
     *
     * @mbggenerated
     */
    int insertSelective(ProductOutstockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_record
     *
     * @mbggenerated
     */
    List<ProductOutstockRecord> selectByExample(ProductOutstockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_record
     *
     * @mbggenerated
     */
    ProductOutstockRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductOutstockRecord record, @Param("example") ProductOutstockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductOutstockRecord record, @Param("example") ProductOutstockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductOutstockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductOutstockRecord record);

    /**
    * @Description: 查询角色可审批的申请列表 
    * @param roles
    * @return List<ProductOutstockRecord>
    * @author mlsong
    * @date 2018年6月4日 下午1:43:51
     */
	List<ProductOutstockRecord> selectRecordsByRole(List<Role> roles);
	
	 String findshTime(Integer id);
}