package com.hj.oa.dao;

import com.hj.oa.bean.ProductOutstockDetail;
import com.hj.oa.bean.ProductOutstockDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductOutstockDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_detail
     *
     * @mbggenerated
     */
    int countByExample(ProductOutstockDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_detail
     *
     * @mbggenerated
     */
    int deleteByExample(ProductOutstockDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_detail
     *
     * @mbggenerated
     */
    int insert(ProductOutstockDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_detail
     *
     * @mbggenerated
     */
    int insertSelective(ProductOutstockDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_detail
     *
     * @mbggenerated
     */
    List<ProductOutstockDetail> selectByExample(ProductOutstockDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_detail
     *
     * @mbggenerated
     */
    ProductOutstockDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductOutstockDetail record, @Param("example") ProductOutstockDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductOutstockDetail record, @Param("example") ProductOutstockDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductOutstockDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_outstock_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductOutstockDetail record);

    /**
    * @Description: 批量出入details 
    * @param products
    * @return int
    * @author mlsong
    * @date 2018年6月4日 下午12:16:15
     */
	int insertList(List<ProductOutstockDetail> details);

	/** 
	* @Description: 查询发货产品总数量
	* @param id
	* @return int
	* @author mlsong
	* @date 2018年6月26日 下午3:54:09
	*/
	int countProductSumByRecordId(Integer id);
}