package com.hj.oa.bean;

import java.io.Serializable;

import org.apache.commons.lang.StringUtils;


public class ApprovalList implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_approval_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_approval_list.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_approval_list.role_list
     *
     * @mbggenerated
     */
    private String roleList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_approval_list.role_name_list
     *
     * @mbggenerated
     */
    private String roleNameList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_approval_list.next_id
     *
     * @mbggenerated
     */
    private Integer nextId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_approval_list.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_approval_list.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_approval_list
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_approval_list.id
     *
     * @return the value of t_approval_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_approval_list.id
     *
     * @param id the value for t_approval_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_approval_list.type
     *
     * @return the value of t_approval_list.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_approval_list.type
     *
     * @param type the value for t_approval_list.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_approval_list.role_list
     *
     * @return the value of t_approval_list.role_list
     *
     * @mbggenerated
     */
    public String getRoleList() {
        return roleList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_approval_list.role_list
     *
     * @param roleList the value for t_approval_list.role_list
     *
     * @mbggenerated
     */
    public void setRoleList(String roleList) {
        this.roleList = roleList == null ? null : roleList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_approval_list.role_name_list
     *
     * @return the value of t_approval_list.role_name_list
     *
     * @mbggenerated
     */
    public String getRoleNameList() {
        return roleNameList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_approval_list.role_name_list
     *
     * @param roleNameList the value for t_approval_list.role_name_list
     *
     * @mbggenerated
     */
    public void setRoleNameList(String roleNameList) {
        this.roleNameList = roleNameList == null ? null : roleNameList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_approval_list.next_id
     *
     * @return the value of t_approval_list.next_id
     *
     * @mbggenerated
     */
    public Integer getNextId() {
        return nextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_approval_list.next_id
     *
     * @param nextId the value for t_approval_list.next_id
     *
     * @mbggenerated
     */
    public void setNextId(Integer nextId) {
        this.nextId = nextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_approval_list.state
     *
     * @return the value of t_approval_list.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_approval_list.state
     *
     * @param state the value for t_approval_list.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_approval_list.description
     *
     * @return the value of t_approval_list.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_approval_list.description
     *
     * @param description the value for t_approval_list.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_list
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ApprovalList other = (ApprovalList) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getRoleList() == null ? other.getRoleList() == null : this.getRoleList().equals(other.getRoleList()))
            && (this.getRoleNameList() == null ? other.getRoleNameList() == null : this.getRoleNameList().equals(other.getRoleNameList()))
            && (this.getNextId() == null ? other.getNextId() == null : this.getNextId().equals(other.getNextId()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_list
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getRoleList() == null) ? 0 : getRoleList().hashCode());
        result = prime * result + ((getRoleNameList() == null) ? 0 : getRoleNameList().hashCode());
        result = prime * result + ((getNextId() == null) ? 0 : getNextId().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_list
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", roleList=").append(roleList);
        sb.append(", roleNameList=").append(roleNameList);
        sb.append(", nextId=").append(nextId);
        sb.append(", state=").append(state);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
    
    public Integer getStartRoleId() {
    	if (StringUtils.isEmpty(roleList)) {
    		return null;
    	}
    	
    	String[] roles = roleList.split("\\,");
    	return Integer.parseInt(roles[0]);
    }
}