package com.hj.oa.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OutstockRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    public OutstockRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRecordIdIsNull() {
            addCriterion("record_id is null");
            return (Criteria) this;
        }

        public Criteria andRecordIdIsNotNull() {
            addCriterion("record_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecordIdEqualTo(Integer value) {
            addCriterion("record_id =", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotEqualTo(Integer value) {
            addCriterion("record_id <>", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThan(Integer value) {
            addCriterion("record_id >", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("record_id >=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThan(Integer value) {
            addCriterion("record_id <", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThanOrEqualTo(Integer value) {
            addCriterion("record_id <=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdIn(List<Integer> values) {
            addCriterion("record_id in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotIn(List<Integer> values) {
            addCriterion("record_id not in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdBetween(Integer value1, Integer value2) {
            addCriterion("record_id between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotBetween(Integer value1, Integer value2) {
            addCriterion("record_id not between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andExpectedOutstockTimeIsNull() {
            addCriterion("expected_outstock_time is null");
            return (Criteria) this;
        }

        public Criteria andExpectedOutstockTimeIsNotNull() {
            addCriterion("expected_outstock_time is not null");
            return (Criteria) this;
        }

        public Criteria andExpectedOutstockTimeEqualTo(Date value) {
            addCriterion("expected_outstock_time =", value, "expectedOutstockTime");
            return (Criteria) this;
        }

        public Criteria andExpectedOutstockTimeNotEqualTo(Date value) {
            addCriterion("expected_outstock_time <>", value, "expectedOutstockTime");
            return (Criteria) this;
        }

        public Criteria andExpectedOutstockTimeGreaterThan(Date value) {
            addCriterion("expected_outstock_time >", value, "expectedOutstockTime");
            return (Criteria) this;
        }

        public Criteria andExpectedOutstockTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("expected_outstock_time >=", value, "expectedOutstockTime");
            return (Criteria) this;
        }

        public Criteria andExpectedOutstockTimeLessThan(Date value) {
            addCriterion("expected_outstock_time <", value, "expectedOutstockTime");
            return (Criteria) this;
        }

        public Criteria andExpectedOutstockTimeLessThanOrEqualTo(Date value) {
            addCriterion("expected_outstock_time <=", value, "expectedOutstockTime");
            return (Criteria) this;
        }

        public Criteria andExpectedOutstockTimeIn(List<Date> values) {
            addCriterion("expected_outstock_time in", values, "expectedOutstockTime");
            return (Criteria) this;
        }

        public Criteria andExpectedOutstockTimeNotIn(List<Date> values) {
            addCriterion("expected_outstock_time not in", values, "expectedOutstockTime");
            return (Criteria) this;
        }

        public Criteria andExpectedOutstockTimeBetween(Date value1, Date value2) {
            addCriterion("expected_outstock_time between", value1, value2, "expectedOutstockTime");
            return (Criteria) this;
        }

        public Criteria andExpectedOutstockTimeNotBetween(Date value1, Date value2) {
            addCriterion("expected_outstock_time not between", value1, value2, "expectedOutstockTime");
            return (Criteria) this;
        }

        public Criteria andOutstockTimeIsNull() {
            addCriterion("outstock_time is null");
            return (Criteria) this;
        }

        public Criteria andOutstockTimeIsNotNull() {
            addCriterion("outstock_time is not null");
            return (Criteria) this;
        }

        public Criteria andOutstockTimeEqualTo(Date value) {
            addCriterion("outstock_time =", value, "outstockTime");
            return (Criteria) this;
        }

        public Criteria andOutstockTimeNotEqualTo(Date value) {
            addCriterion("outstock_time <>", value, "outstockTime");
            return (Criteria) this;
        }

        public Criteria andOutstockTimeGreaterThan(Date value) {
            addCriterion("outstock_time >", value, "outstockTime");
            return (Criteria) this;
        }

        public Criteria andOutstockTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("outstock_time >=", value, "outstockTime");
            return (Criteria) this;
        }

        public Criteria andOutstockTimeLessThan(Date value) {
            addCriterion("outstock_time <", value, "outstockTime");
            return (Criteria) this;
        }

        public Criteria andOutstockTimeLessThanOrEqualTo(Date value) {
            addCriterion("outstock_time <=", value, "outstockTime");
            return (Criteria) this;
        }

        public Criteria andOutstockTimeIn(List<Date> values) {
            addCriterion("outstock_time in", values, "outstockTime");
            return (Criteria) this;
        }

        public Criteria andOutstockTimeNotIn(List<Date> values) {
            addCriterion("outstock_time not in", values, "outstockTime");
            return (Criteria) this;
        }

        public Criteria andOutstockTimeBetween(Date value1, Date value2) {
            addCriterion("outstock_time between", value1, value2, "outstockTime");
            return (Criteria) this;
        }

        public Criteria andOutstockTimeNotBetween(Date value1, Date value2) {
            addCriterion("outstock_time not between", value1, value2, "outstockTime");
            return (Criteria) this;
        }

        public Criteria andShipmentCompanyIsNull() {
            addCriterion("shipment_company is null");
            return (Criteria) this;
        }

        public Criteria andShipmentCompanyIsNotNull() {
            addCriterion("shipment_company is not null");
            return (Criteria) this;
        }

        public Criteria andShipmentCompanyEqualTo(String value) {
            addCriterion("shipment_company =", value, "shipmentCompany");
            return (Criteria) this;
        }

        public Criteria andShipmentCompanyNotEqualTo(String value) {
            addCriterion("shipment_company <>", value, "shipmentCompany");
            return (Criteria) this;
        }

        public Criteria andShipmentCompanyGreaterThan(String value) {
            addCriterion("shipment_company >", value, "shipmentCompany");
            return (Criteria) this;
        }

        public Criteria andShipmentCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("shipment_company >=", value, "shipmentCompany");
            return (Criteria) this;
        }

        public Criteria andShipmentCompanyLessThan(String value) {
            addCriterion("shipment_company <", value, "shipmentCompany");
            return (Criteria) this;
        }

        public Criteria andShipmentCompanyLessThanOrEqualTo(String value) {
            addCriterion("shipment_company <=", value, "shipmentCompany");
            return (Criteria) this;
        }

        public Criteria andShipmentCompanyLike(String value) {
            addCriterion("shipment_company like", value, "shipmentCompany");
            return (Criteria) this;
        }

        public Criteria andShipmentCompanyNotLike(String value) {
            addCriterion("shipment_company not like", value, "shipmentCompany");
            return (Criteria) this;
        }

        public Criteria andShipmentCompanyIn(List<String> values) {
            addCriterion("shipment_company in", values, "shipmentCompany");
            return (Criteria) this;
        }

        public Criteria andShipmentCompanyNotIn(List<String> values) {
            addCriterion("shipment_company not in", values, "shipmentCompany");
            return (Criteria) this;
        }

        public Criteria andShipmentCompanyBetween(String value1, String value2) {
            addCriterion("shipment_company between", value1, value2, "shipmentCompany");
            return (Criteria) this;
        }

        public Criteria andShipmentCompanyNotBetween(String value1, String value2) {
            addCriterion("shipment_company not between", value1, value2, "shipmentCompany");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderNumIsNull() {
            addCriterion("shipment_order_num is null");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderNumIsNotNull() {
            addCriterion("shipment_order_num is not null");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderNumEqualTo(String value) {
            addCriterion("shipment_order_num =", value, "shipmentOrderNum");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderNumNotEqualTo(String value) {
            addCriterion("shipment_order_num <>", value, "shipmentOrderNum");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderNumGreaterThan(String value) {
            addCriterion("shipment_order_num >", value, "shipmentOrderNum");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderNumGreaterThanOrEqualTo(String value) {
            addCriterion("shipment_order_num >=", value, "shipmentOrderNum");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderNumLessThan(String value) {
            addCriterion("shipment_order_num <", value, "shipmentOrderNum");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderNumLessThanOrEqualTo(String value) {
            addCriterion("shipment_order_num <=", value, "shipmentOrderNum");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderNumLike(String value) {
            addCriterion("shipment_order_num like", value, "shipmentOrderNum");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderNumNotLike(String value) {
            addCriterion("shipment_order_num not like", value, "shipmentOrderNum");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderNumIn(List<String> values) {
            addCriterion("shipment_order_num in", values, "shipmentOrderNum");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderNumNotIn(List<String> values) {
            addCriterion("shipment_order_num not in", values, "shipmentOrderNum");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderNumBetween(String value1, String value2) {
            addCriterion("shipment_order_num between", value1, value2, "shipmentOrderNum");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderNumNotBetween(String value1, String value2) {
            addCriterion("shipment_order_num not between", value1, value2, "shipmentOrderNum");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderPicIsNull() {
            addCriterion("shipment_order_pic is null");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderPicIsNotNull() {
            addCriterion("shipment_order_pic is not null");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderPicEqualTo(String value) {
            addCriterion("shipment_order_pic =", value, "shipmentOrderPic");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderPicNotEqualTo(String value) {
            addCriterion("shipment_order_pic <>", value, "shipmentOrderPic");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderPicGreaterThan(String value) {
            addCriterion("shipment_order_pic >", value, "shipmentOrderPic");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderPicGreaterThanOrEqualTo(String value) {
            addCriterion("shipment_order_pic >=", value, "shipmentOrderPic");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderPicLessThan(String value) {
            addCriterion("shipment_order_pic <", value, "shipmentOrderPic");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderPicLessThanOrEqualTo(String value) {
            addCriterion("shipment_order_pic <=", value, "shipmentOrderPic");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderPicLike(String value) {
            addCriterion("shipment_order_pic like", value, "shipmentOrderPic");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderPicNotLike(String value) {
            addCriterion("shipment_order_pic not like", value, "shipmentOrderPic");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderPicIn(List<String> values) {
            addCriterion("shipment_order_pic in", values, "shipmentOrderPic");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderPicNotIn(List<String> values) {
            addCriterion("shipment_order_pic not in", values, "shipmentOrderPic");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderPicBetween(String value1, String value2) {
            addCriterion("shipment_order_pic between", value1, value2, "shipmentOrderPic");
            return (Criteria) this;
        }

        public Criteria andShipmentOrderPicNotBetween(String value1, String value2) {
            addCriterion("shipment_order_pic not between", value1, value2, "shipmentOrderPic");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderNumIsNull() {
            addCriterion("outstock_order_num is null");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderNumIsNotNull() {
            addCriterion("outstock_order_num is not null");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderNumEqualTo(String value) {
            addCriterion("outstock_order_num =", value, "outstockOrderNum");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderNumNotEqualTo(String value) {
            addCriterion("outstock_order_num <>", value, "outstockOrderNum");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderNumGreaterThan(String value) {
            addCriterion("outstock_order_num >", value, "outstockOrderNum");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderNumGreaterThanOrEqualTo(String value) {
            addCriterion("outstock_order_num >=", value, "outstockOrderNum");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderNumLessThan(String value) {
            addCriterion("outstock_order_num <", value, "outstockOrderNum");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderNumLessThanOrEqualTo(String value) {
            addCriterion("outstock_order_num <=", value, "outstockOrderNum");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderNumLike(String value) {
            addCriterion("outstock_order_num like", value, "outstockOrderNum");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderNumNotLike(String value) {
            addCriterion("outstock_order_num not like", value, "outstockOrderNum");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderNumIn(List<String> values) {
            addCriterion("outstock_order_num in", values, "outstockOrderNum");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderNumNotIn(List<String> values) {
            addCriterion("outstock_order_num not in", values, "outstockOrderNum");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderNumBetween(String value1, String value2) {
            addCriterion("outstock_order_num between", value1, value2, "outstockOrderNum");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderNumNotBetween(String value1, String value2) {
            addCriterion("outstock_order_num not between", value1, value2, "outstockOrderNum");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderPicIsNull() {
            addCriterion("outstock_order_pic is null");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderPicIsNotNull() {
            addCriterion("outstock_order_pic is not null");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderPicEqualTo(String value) {
            addCriterion("outstock_order_pic =", value, "outstockOrderPic");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderPicNotEqualTo(String value) {
            addCriterion("outstock_order_pic <>", value, "outstockOrderPic");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderPicGreaterThan(String value) {
            addCriterion("outstock_order_pic >", value, "outstockOrderPic");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderPicGreaterThanOrEqualTo(String value) {
            addCriterion("outstock_order_pic >=", value, "outstockOrderPic");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderPicLessThan(String value) {
            addCriterion("outstock_order_pic <", value, "outstockOrderPic");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderPicLessThanOrEqualTo(String value) {
            addCriterion("outstock_order_pic <=", value, "outstockOrderPic");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderPicLike(String value) {
            addCriterion("outstock_order_pic like", value, "outstockOrderPic");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderPicNotLike(String value) {
            addCriterion("outstock_order_pic not like", value, "outstockOrderPic");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderPicIn(List<String> values) {
            addCriterion("outstock_order_pic in", values, "outstockOrderPic");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderPicNotIn(List<String> values) {
            addCriterion("outstock_order_pic not in", values, "outstockOrderPic");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderPicBetween(String value1, String value2) {
            addCriterion("outstock_order_pic between", value1, value2, "outstockOrderPic");
            return (Criteria) this;
        }

        public Criteria andOutstockOrderPicNotBetween(String value1, String value2) {
            addCriterion("outstock_order_pic not between", value1, value2, "outstockOrderPic");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("operator like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("operator not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNull() {
            addCriterion("operator_id is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNotNull() {
            addCriterion("operator_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdEqualTo(Integer value) {
            addCriterion("operator_id =", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotEqualTo(Integer value) {
            addCriterion("operator_id <>", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThan(Integer value) {
            addCriterion("operator_id >", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("operator_id >=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThan(Integer value) {
            addCriterion("operator_id <", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThanOrEqualTo(Integer value) {
            addCriterion("operator_id <=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIn(List<Integer> values) {
            addCriterion("operator_id in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotIn(List<Integer> values) {
            addCriterion("operator_id not in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdBetween(Integer value1, Integer value2) {
            addCriterion("operator_id between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("operator_id not between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andOutstockTypeIsNull() {
            addCriterion("outstock_type is null");
            return (Criteria) this;
        }

        public Criteria andOutstockTypeIsNotNull() {
            addCriterion("outstock_type is not null");
            return (Criteria) this;
        }

        public Criteria andOutstockTypeEqualTo(Boolean value) {
            addCriterion("outstock_type =", value, "outstockType");
            return (Criteria) this;
        }

        public Criteria andOutstockTypeNotEqualTo(Boolean value) {
            addCriterion("outstock_type <>", value, "outstockType");
            return (Criteria) this;
        }

        public Criteria andOutstockTypeGreaterThan(Boolean value) {
            addCriterion("outstock_type >", value, "outstockType");
            return (Criteria) this;
        }

        public Criteria andOutstockTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("outstock_type >=", value, "outstockType");
            return (Criteria) this;
        }

        public Criteria andOutstockTypeLessThan(Boolean value) {
            addCriterion("outstock_type <", value, "outstockType");
            return (Criteria) this;
        }

        public Criteria andOutstockTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("outstock_type <=", value, "outstockType");
            return (Criteria) this;
        }

        public Criteria andOutstockTypeIn(List<Boolean> values) {
            addCriterion("outstock_type in", values, "outstockType");
            return (Criteria) this;
        }

        public Criteria andOutstockTypeNotIn(List<Boolean> values) {
            addCriterion("outstock_type not in", values, "outstockType");
            return (Criteria) this;
        }

        public Criteria andOutstockTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("outstock_type between", value1, value2, "outstockType");
            return (Criteria) this;
        }

        public Criteria andOutstockTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("outstock_type not between", value1, value2, "outstockType");
            return (Criteria) this;
        }

        public Criteria andOrderNumIsNull() {
            addCriterion("order_num is null");
            return (Criteria) this;
        }

        public Criteria andOrderNumIsNotNull() {
            addCriterion("order_num is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNumEqualTo(Integer value) {
            addCriterion("order_num =", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotEqualTo(Integer value) {
            addCriterion("order_num <>", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumGreaterThan(Integer value) {
            addCriterion("order_num >", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_num >=", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumLessThan(Integer value) {
            addCriterion("order_num <", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumLessThanOrEqualTo(Integer value) {
            addCriterion("order_num <=", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumIn(List<Integer> values) {
            addCriterion("order_num in", values, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotIn(List<Integer> values) {
            addCriterion("order_num not in", values, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumBetween(Integer value1, Integer value2) {
            addCriterion("order_num between", value1, value2, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotBetween(Integer value1, Integer value2) {
            addCriterion("order_num not between", value1, value2, "orderNum");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andShipmentReceiveNumIsNull() {
            addCriterion("shipment_receive_num is null");
            return (Criteria) this;
        }

        public Criteria andShipmentReceiveNumIsNotNull() {
            addCriterion("shipment_receive_num is not null");
            return (Criteria) this;
        }

        public Criteria andShipmentReceiveNumEqualTo(String value) {
            addCriterion("shipment_receive_num =", value, "shipmentReceiveNum");
            return (Criteria) this;
        }

        public Criteria andShipmentReceiveNumNotEqualTo(String value) {
            addCriterion("shipment_receive_num <>", value, "shipmentReceiveNum");
            return (Criteria) this;
        }

        public Criteria andShipmentReceiveNumGreaterThan(String value) {
            addCriterion("shipment_receive_num >", value, "shipmentReceiveNum");
            return (Criteria) this;
        }

        public Criteria andShipmentReceiveNumGreaterThanOrEqualTo(String value) {
            addCriterion("shipment_receive_num >=", value, "shipmentReceiveNum");
            return (Criteria) this;
        }

        public Criteria andShipmentReceiveNumLessThan(String value) {
            addCriterion("shipment_receive_num <", value, "shipmentReceiveNum");
            return (Criteria) this;
        }

        public Criteria andShipmentReceiveNumLessThanOrEqualTo(String value) {
            addCriterion("shipment_receive_num <=", value, "shipmentReceiveNum");
            return (Criteria) this;
        }

        public Criteria andShipmentReceiveNumLike(String value) {
            addCriterion("shipment_receive_num like", value, "shipmentReceiveNum");
            return (Criteria) this;
        }

        public Criteria andShipmentReceiveNumNotLike(String value) {
            addCriterion("shipment_receive_num not like", value, "shipmentReceiveNum");
            return (Criteria) this;
        }

        public Criteria andShipmentReceiveNumIn(List<String> values) {
            addCriterion("shipment_receive_num in", values, "shipmentReceiveNum");
            return (Criteria) this;
        }

        public Criteria andShipmentReceiveNumNotIn(List<String> values) {
            addCriterion("shipment_receive_num not in", values, "shipmentReceiveNum");
            return (Criteria) this;
        }

        public Criteria andShipmentReceiveNumBetween(String value1, String value2) {
            addCriterion("shipment_receive_num between", value1, value2, "shipmentReceiveNum");
            return (Criteria) this;
        }

        public Criteria andShipmentReceiveNumNotBetween(String value1, String value2) {
            addCriterion("shipment_receive_num not between", value1, value2, "shipmentReceiveNum");
            return (Criteria) this;
        }

        public Criteria andShipmentReceivePicIsNull() {
            addCriterion("shipment_receive_pic is null");
            return (Criteria) this;
        }

        public Criteria andShipmentReceivePicIsNotNull() {
            addCriterion("shipment_receive_pic is not null");
            return (Criteria) this;
        }

        public Criteria andShipmentReceivePicEqualTo(String value) {
            addCriterion("shipment_receive_pic =", value, "shipmentReceivePic");
            return (Criteria) this;
        }

        public Criteria andShipmentReceivePicNotEqualTo(String value) {
            addCriterion("shipment_receive_pic <>", value, "shipmentReceivePic");
            return (Criteria) this;
        }

        public Criteria andShipmentReceivePicGreaterThan(String value) {
            addCriterion("shipment_receive_pic >", value, "shipmentReceivePic");
            return (Criteria) this;
        }

        public Criteria andShipmentReceivePicGreaterThanOrEqualTo(String value) {
            addCriterion("shipment_receive_pic >=", value, "shipmentReceivePic");
            return (Criteria) this;
        }

        public Criteria andShipmentReceivePicLessThan(String value) {
            addCriterion("shipment_receive_pic <", value, "shipmentReceivePic");
            return (Criteria) this;
        }

        public Criteria andShipmentReceivePicLessThanOrEqualTo(String value) {
            addCriterion("shipment_receive_pic <=", value, "shipmentReceivePic");
            return (Criteria) this;
        }

        public Criteria andShipmentReceivePicLike(String value) {
            addCriterion("shipment_receive_pic like", value, "shipmentReceivePic");
            return (Criteria) this;
        }

        public Criteria andShipmentReceivePicNotLike(String value) {
            addCriterion("shipment_receive_pic not like", value, "shipmentReceivePic");
            return (Criteria) this;
        }

        public Criteria andShipmentReceivePicIn(List<String> values) {
            addCriterion("shipment_receive_pic in", values, "shipmentReceivePic");
            return (Criteria) this;
        }

        public Criteria andShipmentReceivePicNotIn(List<String> values) {
            addCriterion("shipment_receive_pic not in", values, "shipmentReceivePic");
            return (Criteria) this;
        }

        public Criteria andShipmentReceivePicBetween(String value1, String value2) {
            addCriterion("shipment_receive_pic between", value1, value2, "shipmentReceivePic");
            return (Criteria) this;
        }

        public Criteria andShipmentReceivePicNotBetween(String value1, String value2) {
            addCriterion("shipment_receive_pic not between", value1, value2, "shipmentReceivePic");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeIsNull() {
            addCriterion("receive_time is null");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeIsNotNull() {
            addCriterion("receive_time is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeEqualTo(Date value) {
            addCriterion("receive_time =", value, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeNotEqualTo(Date value) {
            addCriterion("receive_time <>", value, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeGreaterThan(Date value) {
            addCriterion("receive_time >", value, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("receive_time >=", value, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeLessThan(Date value) {
            addCriterion("receive_time <", value, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeLessThanOrEqualTo(Date value) {
            addCriterion("receive_time <=", value, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeIn(List<Date> values) {
            addCriterion("receive_time in", values, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeNotIn(List<Date> values) {
            addCriterion("receive_time not in", values, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeBetween(Date value1, Date value2) {
            addCriterion("receive_time between", value1, value2, "receiveTime");
            return (Criteria) this;
        }

        public Criteria andReceiveTimeNotBetween(Date value1, Date value2) {
            addCriterion("receive_time not between", value1, value2, "receiveTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_outstock_record
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_outstock_record
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}